### ISSUE TITLE
Discovery fails for the second request when PDS is build with relative path to blueprints 

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/platform-discovery-service#11]
An error occurs, when a request is sent the second time and PDS is build with relative blueprints path as in current README:
```
2021-02-19 12:48:29,579 - ERROR - pds.api.controllers.default - An error occurred during discovery process
Traceback (most recent call last):
  File "/home/kml/sodalite/github-repo/platform-discovery-service/src/pds/api/controllers/default.py", line 52, in discover
    safe_storage = SafeStorage.create(
  File "/home/kml/sodalite/github-repo/platform-discovery-service/src/pds/api/storages/safe_storage.py", line 11, in create
    return SafeStorage(
  File "/home/kml/sodalite/github-repo/platform-discovery-service/src/pds/api/storages/safe_storage.py", line 16, in __init__
    super().__init__(path)
  File "/home/kml/sodalite/github-repo/platform-discovery-service/.venv/lib/python3.8/site-packages/opera/storage.py", line 16, in __init__
    path.mkdir(exist_ok=True)
  File "/usr/lib/python3.8/pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../blueprints/torque/.opera'
127.0.0.1 - - [19/Feb/2021 12:48:29] "POST /discover HTTP/1.1" 500 -
```

I was following the instruction in README. To reproduce:

1) Build and run PDS:
```
./generate.sh
python3 -m venv .venv
source .venv/bin/activate
pip install wheel
pip install -r requirements.txt
export PDS_BLUEPRINT_PATH="../blueprints" # this causes the issue
export AUTH_API_KEY="TEST"
cd src/
python3 -m pds.api.run
``` 

2) then simply send the same request twice:
```
$ curl -X POST   http://localhost:8081/discover   -H 'content-type: application/json'   -H 'x-api-key: TEST'   -d '{
    "inputs": {
        "frontend-address": "some-address",
        "user": "some-user",
        "namespace": "TestTorque"
    },
    "platform_type": "torque"
}'
{
  "service_template": {
    "output-torque-tosca": {
      "description": "",
      "value": "tosca_definitions_version: tosca_simple_yaml_1_3 ..."
    }
  },
  "timestamp": "2021-02-19T11:48:25.555522+00:00"
}
$ curl -X POST   http://localhost:8081/discover   -H 'content-type: application/json'   -H 'x-api-key: TEST'   -d '{
    "inputs": {
        "frontend-address": "some-address",
        "user": "some-user",
        "namespace": "TestTorque"
    },
    "platform_type": "torque"
}'
{
  "message": "[Errno 2] No such file or directory: '../blueprints/torque/.opera'"
}
```

Therefore, README should be updated to specify the absolute path to the blueprints

**Comment by kmlTE** [comment]
README was fixed
